version: '3.8'
services:
 mysql_service:
  image: mysql:8
  container_name: mysql_service
  restart: on-failure
  environment:
   MYSQL_ROOT_PASSWORD: mysql
   MYSQL_DATABASE: goSchema
  ports:
   - 3306:3306
  networks:
   - gonetworkapipersona
 demo-crud-api-rest-go:
  build: .
  image: demo-crud-api-rest-go:v1
  container_name: demo-crud-api-rest-go
  ports:
   - 9000:9000
  restart: on-failure
  networks:
   - gonetworkapipersona
  depends_on:
   - mysql_service
networks:
 gonetworkapipersona:
